### ISSUE TITLE
change the user service to ID based from user_handle based

### ISSUE THREAD

**Issue by cdivvela** [ChandraAddala/taskatomic-svc#7]

**Comment by ChandraAddala** [comment]
Any particular reason you are asking for this change? This involves quite a few changes. Unless its absolutely necessary, I am gonna hold off on this change.

The reason I used id for projects and tasks is because, the project name and task name can have spaces or special characters in them. Where as user handle cannot have spaces in them and we should be able to work with handle without any issues.

**Comment by cdivvela** [comment]
going forward, there is no user handle, right? its all based on facebook
login and id.

**Comment by ChandraAddala** [comment]
We are going to store facebook id in the handle column. So we can still work with handle.

**Comment by cdivvela** [comment]
ok. then we are good.

**Comment by ChandraAddala** [comment]
Closing it as we are okay.

**Comment by cdivvela** [comment]
http://www.raywenderlich.com/20482/how-to-choose-the-best-backend-provider-for-your-ios-app-parse-vs-stackmob-vs-appcelerator-cloud-and-more

Damn! Check out Parse
- Free: 1M API Calls, 1M Push notifications (0.07 per 1k over)
- $199: 15M API Calls, 15M Push notifications (0.05 per 1k over)
